// ==========================================
// THE DIVER'S DEX - MASTER DATABASE
// ==========================================
const speciesList = [
    {
        name: "Great White Shark",
        cat: "Shark",
        rarity: "rare",
        danger: 5,
        status: "VU",
        pop: "~3,500 mature individuals",
        size: "4.5m - 6m",
        temp: "12°C - 24°C",
        time: "Day",
        desc: "The ocean's most iconic apex predator. Seeing a Great White underwater is an exercise in scale and presence; they move with a mechanical, effortless power. They are currently Vulnerable due to slow reproductive cycles and years of overfishing. Conservation efforts in places like South Africa and Guadalupe have shown that regulated ecotourism can actually help protect their habitats by giving them economic value beyond their fins.",
        geo: "South Africa, Australia, Guadalupe Island",
        season: "August to March",
        depth: "0m - 1200m",
        funFact: "They can go weeks without eating, relying on energy stored in their massive, oil-rich livers."
    },
    {
        name: "Whale Shark",
        cat: "Shark",
        rarity: "legendary",
		  danger: 1,
        status: "EN",
        pop: "Decreasing (Unknown total)",
        size: "10m - 12m",
        temp: "21°C - 30°C",
        time: "Day",
        desc: "The largest fish in the sea. Encountering a Whale Shark feels like swimming alongside a living submarine. They are Endangered primarily due to vessel strikes and entanglement in fishing gear. Because they spend so much time 'basking' at the surface to feed on plankton, they are highly susceptible to global shipping traffic. Their 'starry' pattern provides camouflage against the sun-dappled surface.",
        geo: "Mexico, Philippines, Ningaloo Reef",
        season: "March to July",
        depth: "0m - 70m",
        funFact: "The spot pattern behind their gills is unique to each individual, like a human fingerprint."
    },
       {
        name: "Orca",
        cat: "Mammal",
        rarity: "legendary",
        img: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==",
        danger: 5,
        status: "DD",
        pop: "50,000",
        size: "6m - 8m",
        temp: "0°C - 30°C",
        time: "Day/Night",
        desc: "The ocean's apex predator.",
        geo: "Global",
        season: "Varies",
        depth: "0m - 100m",
        funFact: "They stay with their moms forever."
    },
    {
        name: "Giant Oceanic Manta Ray",
        cat: "Ray",
        rarity: "legendary",
        danger: 1,
        status: "EN",
        pop: "Significant decline (Unknown)",
        size: "5m - 7m",
        temp: "20°C - 28°C",
        time: "Day",
        desc: "Deep-sea voyagers of the Manta world. Unlike reef mantas, the Oceanic variety has a stark, geometric black-and-white pattern. They are now Endangered because they are frequently caught as bycatch in commercial tuna fisheries and hunted for their gill rakers used in traditional medicine. They have been observed recognizing themselves in mirrors, a feat only shared by highly advanced animals.",
        geo: "Socorro Island, Maldives, Thailand",
        season: "Varies by location",
        depth: "0m - 50m",
        funFact: "They have the largest brain-to-body ratio of any cold-blooded fish."
    },
    {
        name: "Scalloped Hammerhead",
        cat: "Shark",
        rarity: "epic",
        danger: 3,
        status: "CR",
        pop: "Critically low in several regions",
        size: "2.5m - 4m",
        temp: "22°C - 26°C",
        time: "Day",
        desc: "Famed for their wide, flat heads (cephalofoils). They are Critically Endangered due to the shark fin trade; their schooling behavior makes them easy targets for large-scale fishing. In the water, they are incredibly shy. They use their wide heads to house extra sensory organs that detect the electrical heartbeats of prey buried in the sand. Seeing a school of hundreds at a seamount is one of the world's greatest diving spectacles.",
        geo: "Galapagos, Cocos Island, Malpelo",
        season: "June to September",
        depth: "20m - 500m",
        funFact: "They can tan! Their skin darkens when they spend long periods in shallow, sunlit water."
    },
    {
        name: "Blue Whale",
        cat: "Mammal",
        rarity: "legendary",
        danger: 1,
        status: "EN",
        pop: "~10,000 - 25,000",
        size: "24m - 30m",
        temp: "0°C - 20°C",
        time: "Day",
        desc: "The largest animal to ever inhabit the Earth. Seeing a Blue Whale underwater is nearly impossible due to their speed and deep-water nature, but for a diver, their song can be heard from miles away. They are Endangered due to historic commercial whaling and current threats from ship strikes and climate change affecting their krill food source.",
        geo: "California, Sri Lanka, Azores",
        season: "June to October",
        depth: "0m - 100m",
        funFact: "A Blue Whale's heart is the size of a bumper car, and its tongue alone weighs as much as an entire elephant."
    },
    {
        name: "Humpback Whale",
        cat: "Mammal",
        rarity: "epic",
        danger: 1,
        status: "LC",
        pop: "~84,000",
        size: "13m - 16m",
        temp: "1°C - 25°C",
        time: "Day",
        desc: "Famous for their haunting songs and acrobatic breaching. Humpbacks are a 'success story' of conservation, having moved from Endangered to Least Concern in many regions. Divers often encounter them in 'heat runs' or mothers with calves. Their massive pectoral fins are the longest appendages of any animal, reaching up to 5 meters.",
        geo: "Tonga, Silver Bank, Hawaii",
        season: "January to April",
        depth: "0m - 50m",
        funFact: "Only the males sing, and all males in a single population sing the exact same song, which evolves slowly every year."
    },
    {
        name: "Dugong",
        cat: "Mammal",
        rarity: "rare",
        danger: 1,
        status: "VU",
        pop: "Unknown (Highly fragmented)",
        size: "2.5m - 3m",
        temp: "20°C - 30°C",
        time: "Day",
        desc: "The gentle 'Sea Cow' of the Indo-Pacific. Dugongs are strictly vegetarians, grazing on seagrass meadows. They are Vulnerable due to habitat loss and water pollution. Unlike Manatees, they have a fluked tail like a whale. Seeing one in the wild is rare as they are incredibly shy and can hold their breath for up to 6 minutes.",
        geo: "Egypt (Marsa Alam), Australia, Philippines",
        season: "Year-round",
        depth: "1m - 10m",
        funFact: "Dugongs are the inspiration behind ancient mermaid myths and are more closely related to elephants than to whales."
    },
    {
        name: "Bottlenose Dolphin",
        cat: "Mammal",
        rarity: "common",
        danger: 2,
        status: "LC",
        pop: "~600,000+",
        size: "2m - 4m",
        temp: "10°C - 32°C",
        time: "Day/Night",
        desc: "The most famous of all marine mammals. Highly intelligent and social, they often ride the bow wakes of boats. While Least Concern globally, they face localized threats from entanglement and acoustic pollution. Divers often hear their clicks and whistles long before the pod gracefully zips past them in a blur of grey.",
        geo: "Global coastal waters",
        season: "Year-round",
        depth: "0m - 50m",
        funFact: "Dolphins have individual 'signature whistles' that function exactly like human names."
    },
    {
        name: "Minke Whale",
        cat: "Mammal",
        rarity: "uncommon",
        danger: 1,
        status: "LC",
        pop: "~200,000",
        size: "7m - 10m",
        temp: "2°C - 25°C",
        time: "Day",
        desc: "The smallest of the great whales. Dwarf Minke Whales are famously curious in the Great Barrier Reef, where they will actually approach stationary divers and circle them for hours. They have a sleek, torpedo-like shape and a distinct white band on their pectoral fins. They are one of the fastest swimmers among the whales.",
        geo: "Australia (GBR), Scotland, Norway",
        season: "June to July (Australia)",
        depth: "0m - 100m",
        funFact: "Minke whales are known for 'boings'—mysterious underwater sounds that took scientists decades to identify as whale calls."
    },
    {
        name: "Giant Oceanic Manta Ray",
        cat: "Ray",
        rarity: "legendary",
        danger: 1,
        status: "EN",
        pop: "Decreasing (Significant)",
        size: "5m - 7m",
        temp: "20°C - 28°C",
        time: "Day",
        desc: "Deep-sea voyagers of the Manta world. Unlike reef mantas, the Oceanic variety has a stark, geometric black-and-white pattern. They are now Endangered because they are frequently caught as bycatch in commercial tuna fisheries. They have been observed recognizing themselves in mirrors, a feat only shared by a few highly advanced animals.",
        geo: "Socorro Island, Maldives, Thailand",
        season: "Varies by location",
        depth: "0m - 50m",
        funFact: "They have the largest brain-to-body ratio of any fish, and their cephalic fins (horns) can be rolled up like scrolls."
    },
    {
        name: "Spotted Eagle Ray",
        cat: "Ray",
        rarity: "rare",
        danger: 2,
        status: "EN",
        pop: "Decreasing",
        size: "1.5m - 3m (wingspan)",
        temp: "24°C - 30°C",
        time: "Day",
        desc: "Often seen 'flying' in formation, these rays are stunning due to their white-spotted backs and long, whip-like tails. They are Endangered due to overfishing and habitat destruction. They use their duck-bill shaped snouts to dig for mollusks in the sand. Seeing a school of them gliding past a reef wall is a highlight for any diver.",
        geo: "Caribbean, Maldives, Galapagos",
        season: "Year-round",
        depth: "1m - 80m",
        funFact: "They are known to jump completely out of the water to escape predators or shake off parasites."
    },
    {
        name: "Southern Stingray",
        cat: "Ray",
        rarity: "common",
        danger: 2,
        status: "NT",
        pop: "Stable (Local declines)",
        size: "1.2m - 1.5m",
        temp: "22°C - 30°C",
        time: "Day/Night",
        desc: "The quintessential Caribbean stingray. They are often found partially buried in the sand or gathering at 'Stingray Cities' where they've become accustomed to humans. While mostly docile, they have a venomous barb at the base of their tail for defense. They are Near Threatened due to unregulated tourism and coastal development.",
        geo: "Cayman Islands, Bahamas, Florida",
        season: "Year-round",
        depth: "0m - 25m",
        funFact: "Stingrays use electrical sensors called 'Ampullae of Lorenzini' to find prey hidden under the sand."
    },
    {
        name: "Smalltooth Sawfish",
        cat: "Ray",
        rarity: "legendary",
        danger: 3,
        status: "CR",
        pop: "Extremely Low (~2,000-5,000)",
        size: "4m - 5m",
        temp: "18°C - 30°C",
        time: "Night/Day",
        desc: "Actually a type of ray, not a shark. Its 'saw' (rostrum) is lined with sensitive teeth to detect and stun fish. They are Critically Endangered; their saws become easily entangled in any type of fishing net. They were once common throughout the Atlantic but are now restricted to a few strongholds in Florida and the Bahamas.",
        geo: "Florida Everglades, Bahamas",
        season: "Spring (March-May)",
        depth: "0m - 100m",
        funFact: "Sawfish can give birth to up to 20 pups, and the pups' saws are covered in a thick gel at birth so they don't hurt the mother."
    },
    {
        name: "Blue Spotted Ribbontail Ray",
        cat: "Ray",
        rarity: "common",
        danger: 2,
        status: "NT",
        pop: "Unknown",
        size: "25cm - 35cm",
        temp: "24°C - 29°C",
        time: "Night",
        desc: "A small, colorful ray with bright neon-blue spots. They are shy and usually found hiding under coral ledges during the day, coming out at night to hunt. They are Near Threatened because they are popular in the aquarium trade and their coral reef habitats are under stress from warming oceans.",
        geo: "Red Sea, Great Barrier Reef, Indonesia",
        season: "Year-round",
        depth: "1m - 20m",
        funFact: "If threatened, their blue spots act as a warning (aposematism) to predators that they are venomous."
    }, 
    {
        name: "Blue-Ringed Octopus",
        cat: "Invertebrate",
        rarity: "epic",
        danger: 5,
        status: "LC",
        pop: "Stable / Common",
        size: "12cm - 20cm",
        temp: "22°C - 28°C",
        time: "Day/Night",
        desc: "One of the world's most venomous marine animals. Despite its small size and docile nature, its tetrodotoxin is 1,200 times more toxic than cyanide. Divers usually find them in tide pools or shallow reefs. They only show their namesake blue rings when threatened; otherwise, they are expertly camouflaged against the sand and rubble.",
        geo: "Western Pacific, Australia, Indonesia",
        season: "Year-round",
        depth: "1m - 20m",
        funFact: "A single octopus carries enough venom to kill 26 adult humans within minutes, and there is currently no known antivenom."
    },
    {
        name: "Giant Spider Crab",
        cat: "Invertebrate",
        rarity: "rare",
        danger: 2,
        status: "DD",
        pop: "Unknown (Deep water)",
        size: "Up to 3.8m (leg span)",
        temp: "10°C - 15°C",
        time: "Night",
        desc: "The largest known arthropod. These spindly giants look like something out of a science fiction movie. They inhabit the deep vents and sandy shelves of the Pacific. Because they live so deep, they are rarely seen by recreational divers unless they migrate to shallower waters for mating. Their orange bodies are covered in bumps that help them blend into the sea floor.",
        geo: "Japan (Izu Islands), Taiwan",
        season: "Winter (Mating migration)",
        depth: "50m - 600m",
        funFact: "They can live to be 100 years old, making them some of the longest-lived creatures in the ocean."
    },
    {
        name: "Giant Pacific Octopus",
        cat: "Invertebrate",
        rarity: "rare",
        danger: 2,
        status: "LC",
        pop: "Stable",
        size: "3m - 5m",
        temp: "8°C - 12°C",
        time: "Night",
        desc: "The undisputed heavyweight of the octopus world. These highly intelligent cephalopods are masters of disguise, able to change not just their color, but the texture of their skin to match kelp or rock. They are known to solve puzzles, open jars, and even recognize individual human divers. They are terminal spawners, meaning they die shortly after their eggs hatch.",
        geo: "North Pacific (California to Japan)",
        season: "Year-round",
        depth: "0m - 1500m",
        funFact: "They have three hearts and blue blood (copper-based hemocyanin), which is more efficient at carrying oxygen in cold, low-oxygen water."
    },
        {
        name: "Great Barracuda",
        cat: "Fish",
        rarity: "uncommon",
        danger: 3,
        status: "LC",
        pop: "Stable",
        size: "1.5m - 2m",
        temp: "24°C - 30°C",
        time: "Day",
        desc: "The silver sentinel of the reef. Barracudas are known for their jutting lower jaw and impressive array of sharp, fang-like teeth. They are curious predators that often follow divers, attracted to shiny objects that mimic the flash of fish scales. While they look menacing, unprovoked attacks are extremely rare. They are masters of the 'burst' swim, hitting speeds of up to 58 km/h.",
        geo: "Caribbean, Red Sea, Indo-Pacific",
        season: "Year-round",
        depth: "1m - 100m",
        funFact: "Large barracudas are often solitary, while the younger, smaller ones congregate in massive, shimmering schools for protection."
    },
    {
        name: "Ocean Sunfish",
        cat: "Fish",
        rarity: "legendary",
        danger: 1,
        status: "VU",
        pop: "Decreasing",
        size: "1.8m - 3.3m",
        temp: "10°C - 20°C",
        time: "Day",
        desc: "Also known as the 'Mola Mola,' this is the heaviest bony fish in the world. It looks like a giant floating head with wings. They are often found basking on their sides at the surface to warm up after deep dives into cold water. They are Vulnerable due to being frequently caught as bycatch in gillnets. Their diet consists almost entirely of jellyfish.",
        geo: "Global Temperate & Tropical Oceans",
        season: "Summer/Fall",
        depth: "0m - 600m",
        funFact: "A single female can produce up to 300 million eggs at a time—more than any other known vertebrate."
    },
    {
        name: "Lionfish",
        cat: "Fish",
        rarity: "common",
        danger: 4,
        status: "LC",
        pop: "Invasive / Rapidly Increasing",
        size: "30cm - 45cm",
        temp: "22°C - 30°C",
        time: "Dusk/Night",
        desc: "Stunning but destructive. Covered in venomous spines, the Lionfish is a major invasive species in the Atlantic and Caribbean, where it has no natural predators and devours native reef fish at an alarming rate. Divers are often encouraged to hunt them to protect the reef. Their fan-like pectoral fins are used to corner prey before they swallow it whole in a lightning-fast strike.",
        geo: "Indo-Pacific (Native), Caribbean (Invasive)",
        season: "Year-round",
        depth: "1m - 300m",
        funFact: "Their stomach can expand up to 30 times its normal size after a particularly large meal."
    },
    {
        name: "Leafy Seadragon",
        cat: "Fish",
        rarity: "legendary",
        danger: 1,
        status: "LC",
        pop: "Stable (Protected)",
        size: "20cm - 24cm",
        temp: "13°C - 19°C",
        time: "Day",
        desc: "The ultimate master of camouflage. Related to seahorses, these creatures look exactly like floating pieces of seaweed thanks to leaf-like appendages all over their bodies. They are found only in the cold waters of Southern Australia. They are highly protected by law, and seeing one is considered a 'bucket list' moment for underwater photographers.",
        geo: "Southern Australia",
        season: "October to March",
        depth: "5m - 30m",
        funFact: "Like seahorses, the male Leafy Seadragon is the one who carries the eggs, but instead of a pouch, he carries them on a 'brood patch' under his tail."
    },
    {
        name: "Napoleon Wrasse",
        cat: "Fish",
        rarity: "rare",
        danger: 1,
        status: "EN",
        pop: "Unknown (Severely Fragmented)",
        size: "1.5m - 2.3m",
        temp: "25°C - 30°C",
        time: "Day",
        desc: "Also called the Humphead Wrasse, these giants are the kings of the coral reef. They are easily identified by their thick lips and the prominent hump on their foreheads. They are Endangered due to the luxury live food trade in Asia. They are one of the few predators of toxic animals like the Crown-of-Thorns starfish, making them vital to reef health.",
        geo: "Indo-Pacific, Red Sea",
        season: "Year-round",
        depth: "1m - 100m",
        funFact: "They are protogynous hermaphrodites—some females can transform into males as they age and grow larger."
    },
    {
        name: "Chambered Nautilus",
        cat: "Invertebrate",
        rarity: "epic",
        danger: 1,
        status: "VU",
        pop: "Decreasing",
        size: "15cm - 25cm",
        temp: "10°C - 20°C",
        time: "Night",
        desc: "A living fossil that has remained largely unchanged for 500 million years. This cephalopod lives in a beautiful spiral shell divided into chambers, which it uses to regulate buoyancy. They spend their days in the extreme deep (up to 700m) and migrate up to the reefs at night to feed. They are Vulnerable due to over-harvesting for their ornamental shells.",
        geo: "Palau, Philippines, Indonesia",
        season: "Year-round",
        depth: "100m - 700m",
        funFact: "Unlike their cousins (octopus/squid), the Nautilus has about 90 small tentacles and lacks an ink sac."
    },		
	    {
        name: "Giant Moray Eel",
        cat: "Fish",
        rarity: "uncommon",
        danger: 3,
        status: "LC",
        pop: "Stable",
        size: "2m - 3m",
        temp: "24°C - 30°C",
        time: "Night/Day",
        desc: "The heavyweights of the eel world. Giant Morays are often seen with just their heads protruding from reef crevices, rhythmicly opening and closing their mouths to pump water over their gills. While they look aggressive, they are generally peaceful unless provoked. They have a secondary set of 'pharyngeal' jaws in their throat that reach forward to grab prey and pull it down.",
        geo: "Indo-Pacific, Red Sea, East Africa",
        season: "Year-round",
        depth: "1m - 50m",
        funFact: "They often engage in cooperative hunting with Groupers, a rare example of two different species working together to find food."
    },
    {
        name: "Banded Sea Krait",
        cat: "Reptile",
        rarity: "uncommon",
        danger: 5,
        status: "LC",
        pop: "Stable",
        size: "1m - 1.5m",
        temp: "26°C - 31°C",
        time: "Day/Night",
        desc: "A highly venomous sea snake easily recognized by its blue and black bands. They are amphibious, meaning they must come onto land to digest food, skin-shed, and lay eggs. While their venom is incredibly potent, they are famously docile and rarely bite humans unless stepped on or handled. They hunt by poking their heads into small coral holes to find sleeping fish.",
        geo: "Southeast Asia, Australia, Pacific Islands",
        season: "Year-round",
        depth: "0m - 20m",
        funFact: "The tail of a Sea Krait looks almost exactly like its head; this 'two-headed' appearance confuses predators into thinking the snake is always watching them."
    },
    {
        name: "Stonefish",
        cat: "Fish",
        rarity: "rare",
        danger: 5,
        status: "LC",
        pop: "Stable",
        size: "30cm - 40cm",
        temp: "24°C - 28°C",
        time: "Day/Night",
        desc: "The most venomous fish in the world. As the ultimate master of camouflage, the Stonefish looks exactly like an encrusted rock or a piece of coral rubble. It sits perfectly still, waiting for small fish to swim by before engulfing them in a fraction of a second. Its dorsal spines are strong enough to pierce through a rubber boot, delivering a neurotoxin that causes excruciating pain.",
        geo: "Indo-Pacific, Red Sea",
        season: "Year-round",
        depth: "1m - 30m",
        funFact: "Stonefish can survive out of water for up to 24 hours by absorbing oxygen through their skin, often being stepped on during low tide."
    },
    {
        name: "Mimic Octopus",
        cat: "Invertebrate",
        rarity: "legendary",
        danger: 1,
        status: "DD",
        pop: "Unknown",
        size: "50cm - 60cm",
        temp: "25°C - 29°C",
        time: "Day",
        desc: "A marvel of the 'muck diving' world. Unlike other octopuses that just change color, the Mimic Octopus actually changes its shape and movement to impersonate other toxic animals. It has been observed mimicking lionfish, sea snakes, and flatfish to scare away specific predators. They are highly intelligent and usually inhabit silt-heavy, sandy bottoms near river mouths.",
        geo: "Indonesia (Lembeh Strait), Philippines",
        season: "Year-round",
        depth: "2m - 15m",
        funFact: "It is the only known marine animal that can intelligently decide which animal to mimic based on what kind of predator is currently threatening it."
    },
    {
        name: "Electric Ray",
        cat: "Ray",
        rarity: "rare",
        danger: 4,
        status: "DD",
        pop: "Unknown",
        size: "0.5m - 1.5m",
        temp: "15°C - 25°C",
        time: "Night",
        desc: "Also known as the Torpedo Ray, these thick-bodied rays possess specialized kidney-shaped organs that can generate a powerful electric discharge. They use this shock to stun prey and defend against predators. A large individual can produce a shock of up to 220 volts—enough to knock a human unconscious. They are slow swimmers and usually stay partially buried in the mud.",
        geo: "Mediterranean, Atlantic, Pacific",
        season: "Year-round",
        depth: "5m - 200m",
        funFact: "Ancient Greeks and Romans used the shocks from these rays to treat headaches and gout, making them one of the earliest forms of 'electrotherapy.'"
    },
    {
        name: "Giant Frogfish",
        cat: "Fish",
        rarity: "rare",
        danger: 1,
        status: "LC",
        pop: "Stable",
        size: "10cm - 30cm",
        temp: "24°C - 30°C",
        time: "Day",
        desc: "The ultimate 'grumpy' fish. Frogfish don't really swim; they use their pectoral fins like legs to 'walk' across the seafloor. They are masters of camouflage, changing color to match the sponges around them. They have a built-in fishing rod (illicium) on their head with a lure (esca) at the end to trick smaller fish into range.",
        geo: "Indo-Pacific, Red Sea",
        season: "Year-round",
        depth: "1m - 40m",
        funFact: "They have one of the fastest strike speeds of any vertebrate—opening their mouths and engulfing prey in just 6 milliseconds."
    },
    {
        name: "Ornate Ghost Pipefish",
        cat: "Fish",
        rarity: "legendary",
        danger: 1,
        status: "DD",
        pop: "Unknown",
        size: "8cm - 12cm",
        temp: "25°C - 29°C",
        time: "Day",
        desc: "Looking more like a piece of ornate weed than a fish, the Ghost Pipefish is a favorite for macro photographers. They are masters of 'hiding in plain sight,' often hovering upside down near crinoids (sea lilies) to match their patterns perfectly. They are only found in the wild for a few months a year when they come to the reef to breed.",
        geo: "Indo-Pacific",
        season: "August to November",
        depth: "5m - 25m",
        funFact: "Unlike their relatives, the seahorses, it is the female Ghost Pipefish that broods the eggs in a special pouch formed by her pelvic fins."
    },
    {
        name: "Yellow-Lipped Sea Krait",
        cat: "Reptile",
        rarity: "uncommon",
        danger: 5,
        status: "LC",
        pop: "Stable",
        size: "1.2m - 1.5m",
        temp: "26°C - 30°C",
        time: "Day/Night",
        desc: "A beautiful but lethal reptile. The Yellow-Lipped Sea Krait spends equal time on land and in the water. Because they have a paddle-shaped tail, they are incredibly graceful swimmers. While they possess neurotoxic venom many times stronger than a cobra's, they are extremely gentle toward divers and only bite if they feel their life is in immediate danger.",
        geo: "Southeast Asia, Australia",
        season: "Year-round",
        depth: "0m - 15m",
        funFact: "They often hunt in huge groups alongside predatory fish like Goatfish and Trevally, flushing prey out of coral crevices for each other."
    },
    {
        name: "Flamboyant Cuttlefish",
        cat: "Invertebrate",
        rarity: "epic",
        danger: 4,
        status: "DD",
        pop: "Unknown",
        size: "6cm - 8cm",
        temp: "24°C - 28°C",
        time: "Day",
        desc: "A tiny, walking tank of color. While most cuttlefish use camouflage to hide, the Flamboyant Cuttlefish uses bright pink, yellow, and purple pulses to warn predators that it is highly toxic. It is the only cuttlefish known to 'walk' along the seafloor using its tentacles. They are a crown jewel for divers visiting the 'muck' sites of the Indo-Pacific.",
        geo: "Indonesia, Philippines, Northern Australia",
        season: "Year-round",
        depth: "3m - 80m",
        funFact: "Their muscle tissue contains a unique toxin that is just as lethal as the venom of the Blue-Ringed Octopus."
    }


	

];








    //helpful for checking your progress in the browser console
console.log(`Dex Database initialized with ${speciesList.length} species.`);
