const speciesList = [
    {
        name: "Orca",
        cat: "Mammal",
        rarity: "legendary",
        size: "8.0m",
        geo: "Global / Arctic to Tropical",
        temp: "2°C - 24°C",
        depth: "0m - 1000m",
        status: "DD", 
        danger: 5,
        population: "Approx. 50,000",
        time: "Day/Night",
        season: "All Year",
        diet: "Carnivore",
        desc: "The Orca, or Killer Whale, is the ocean's most formidable apex predator. Despite their name, they are actually the largest species of dolphin. They live in complex matrilineal family pods and are famous for their unique 'cultures,' where different pods specialize in specific hunting techniques passed down through generations. From beaching themselves to catch seals to creating waves to knock penguins off ice, their intelligence is unrivaled in the marine world.",
        funFact: "Orcas are one of the few species that undergo menopause and live long lives as grandmothers to help raise the pod's youth.",
        img: "" 
    },
{
    name: "Great White Shark",
    cat: "Shark",
    rarity: "legendary",
    status: "VU",
    size: "4.5m - 6.0m",
    danger: 5,
    population: "Approx. 3,500",
    depth: "0m - 1200m",
    temp: "12°C - 24°C",
    time: "Day/Night",
    season: "All Year",
    diet: "Carnivore",
    geo: "Global / Coastal",
    desc: "The world's largest known predatory fish. Great Whites are famous for their breaching behavior, where they launch their entire bodies out of the water while hunting seals. They possess an incredible sense of smell and can detect a single drop of blood in 100 liters of water.",
    funFact: "They don't have bones! Their skeleton is made entirely of cartilage, just like your nose and ears."
},
{
    name: "Blue-Ringed Octopus",
    cat: "Cephalopod",
    rarity: "epic",
    status: "LC",
    size: "12cm - 20cm",
    danger: 5,
    population: "Stable",
    depth: "0m - 20m",
    temp: "18°C - 28°C",
    time: "Day",
    season: "Spring/Summer",
    diet: "Carnivore",
    geo: "Indo-Pacific",
    desc: "Despite its small size and beautiful glowing blue rings, this is one of the world's most venomous marine animals. The rings only appear when the octopus feels threatened, serving as a bright warning to predators to stay away.",
    funFact: "Their venom is 1,000 times more powerful than cyanide, yet they are only the size of a golf ball."
},
{
    name: "Manta Ray",
    cat: "Ray",
    rarity: "epic",
    status: "VU",
    size: "7.0m (Wing span)",
    danger: 0,
    population: "Decreasing",
    depth: "0m - 120m",
    temp: "20°C - 30°C",
    time: "Day",
    season: "All Year",
    diet: "Planktivore",
    geo: "Tropical Waters",
    desc: "These 'birds of the sea' are gentle giants. Unlike stingrays, Mantas do not have a venomous tail barb. They spend their lives filter-feeding on tiny plankton and are known for their high intelligence and curiosity toward divers.",
    funFact: "Manta Rays have the largest brain-to-body ratio of any fish in the ocean."
},
{
    name: "Green Sea Turtle",
    cat: "Turtle",
    rarity: "rare",
    status: "EN",
    size: "1.0m - 1.2m",
    danger: 0,
    population: "Approx. 85,000",
    depth: "0m - 50m",
    temp: "20°C - 25°C",
    time: "Day",
    season: "Nesting Season",
    diet: "Herbivore",
    geo: "Global / Subtropical",
    desc: "The only sea turtle that is a strict herbivore as an adult, which gives their fat a greenish color—hence their name. They travel thousands of miles between their feeding grounds and the beaches where they were hatched.",
    funFact: "They can hold their breath for up to five hours while sleeping underwater!"
},
{
    name: "Lionfish",
    cat: "Fish",
    rarity: "uncommon",
    status: "LC",
    size: "30cm - 45cm",
    danger: 3,
    population: "Invasive/Abundant",
    depth: "1m - 300m",
    temp: "22°C - 28°C",
    time: "Dusk/Night",
    season: "All Year",
    diet: "Carnivore",
    geo: "Indo-Pacific / Atlantic",
    desc: "Beautiful but destructive, the Lionfish is covered in venomous spines. In the Atlantic, they are a major invasive species because they have no natural predators and a massive appetite for smaller reef fish.",
    funFact: "A female lionfish can lay up to 2 million eggs per year."
}

];
