const speciesList = [
    {
        name: "Orca",
        cat: "Mammal",
        rarity: "legendary",
        size: "8.0m",
        geo: "Global / Arctic to Tropical",
        temp: "2°C - 24°C",
        depth: "0m - 1000m",
        status: "DD", 
        danger: 5,
        population: "Approx. 50,000",
        time: "Day/Night",
        season: "All Year",
        diet: "Carnivore",
        desc: "The Orca, or Killer Whale, is the ocean's most formidable apex predator. Despite their name, they are actually the largest species of dolphin. They live in complex matrilineal family pods and are famous for their unique 'cultures,' where different pods specialize in specific hunting techniques passed down through generations. From beaching themselves to catch seals to creating waves to knock penguins off ice, their intelligence is unrivaled in the marine world.",
        funFact: "Orcas are one of the few species that undergo menopause and live long lives as grandmothers to help raise the pod's youth."
    },
    {
        name: "Great White Shark",
        cat: "Shark",
        rarity: "legendary",
        status: "VU",
        size: "4.5m - 6.0m",
        danger: 5,
        population: "Approx. 3,500",
        depth: "0m - 1200m",
        temp: "12°C - 24°C",
        time: "Day/Night",
        season: "All Year",
        diet: "Carnivore",
        geo: "Global / Coastal",
        desc: "The world's largest known predatory fish and a primary apex predator of the coastal ceiling. Great Whites are famous for their breaching behavior, where they launch their entire massive bodies out of the water while hunting pinnipeds. They possess an incredible sense of smell and can detect a single drop of blood in 100 liters of water. Their rows of serrated teeth are constantly replaced throughout their lifetime, ensuring they remain lethal hunters for decades.",
        funFact: "They don't have bones! Their skeleton is made entirely of cartilage, just like your nose and ears."
    },
    {
        name: "Blue-Ringed Octopus",
        cat: "Cephalopod",
        rarity: "epic",
        status: "LC",
        size: "12cm - 20cm",
        danger: 5,
        population: "Stable",
        depth: "0m - 20m",
        temp: "18°C - 28°C",
        time: "Day",
        season: "Spring/Summer",
        diet: "Carnivore",
        geo: "Indo-Pacific",
        desc: "Despite its small size and beautiful glowing blue rings, this is one of the world's most venomous marine animals. The rings only appear when the octopus feels threatened, serving as a high-voltage warning to predators to stay away. They carry enough tetrodotoxin to kill twenty-six adult humans within minutes, and currently, there is no known antivenom. They spend most of their time hiding in crevices or under shells, hunting for small crabs and shrimp.",
        funFact: "Their venom is 1,000 times more powerful than cyanide, yet they are only the size of a golf ball."
    },
    {
        name: "Manta Ray",
        cat: "Ray",
        rarity: "epic",
        status: "VU",
        size: "7.0m (Wing span)",
        danger: 0,
        population: "Decreasing",
        depth: "0m - 120m",
        temp: "20°C - 30°C",
        time: "Day",
        season: "All Year",
        diet: "Planktivore",
        geo: "Tropical Waters",
        desc: "Often referred to as the 'birds of the sea,' these gentle giants are among the most charismatic megafauna in the ocean. Unlike stingrays, Mantas do not have a venomous tail barb and pose no threat to humans. They spend their lives filter-feeding on tiny plankton, using their cephalic fins to funnel water into their mouths. They are known for their high intelligence, massive brain-to-body ratio, and frequent curiosity toward scuba divers.",
        funFact: "Manta Rays have the largest brain-to-body ratio of any fish in the ocean."
    },
    {
        name: "Green Sea Turtle",
        cat: "Turtle",
        rarity: "rare",
        status: "EN",
        size: "1.0m - 1.2m",
        danger: 0,
        population: "Approx. 85,000",
        depth: "0m - 50m",
        temp: "20°C - 25°C",
        time: "Day",
        season: "Nesting Season",
        diet: "Herbivore",
        geo: "Global / Subtropical",
        desc: "The only sea turtle that is a strict herbivore as an adult, primarily grazing on seagrass and algae. This diet gives their internal fat a greenish color, which is how they earned their common name. They are incredible navigators, traveling thousands of miles between their feeding grounds and the exact same beaches where they were hatched years prior. As they age, their shells become a complex ecosystem, often playing host to barnacles and small fish.",
        funFact: "They can hold their breath for up to five hours while sleeping underwater!"
    },
    {
        name: "Lionfish",
        cat: "Fish",
        rarity: "uncommon",
        status: "LC",
        size: "30cm - 45cm",
        danger: 3,
        population: "Invasive/Abundant",
        depth: "1m - 300m",
        temp: "22°C - 28°C",
        time: "Dusk/Night",
        season: "All Year",
        diet: "Carnivore",
        geo: "Indo-Pacific / Atlantic",
        desc: "Beautiful but highly destructive, the Lionfish is covered in fan-like venomous spines that serve as a potent defense mechanism. In the Atlantic and Caribbean, they are a major invasive species because they have no natural predators and a massive appetite for juvenile reef fish. Their hunting style is unique; they use their expanded pectoral fins to corner prey before striking with lightning speed. Efforts are underway globally to manage their population through specialized culling programs.",
        funFact: "A female lionfish can lay up to 2 million eggs per year."
    },
    {
        name: "Clown Anemonefish",
        cat: "Fish",
        rarity: "common",
        status: "LC",
        size: "10cm",
        danger: 0,
        population: "Stable",
        depth: "1m - 15m",
        temp: "24°C - 28°C",
        time: "Day",
        season: "All Year",
        diet: "Omnivore",
        geo: "Indo-Pacific",
        desc: "Famous for its symbiotic relationship with sea anemones, this small fish is a staple of tropical coral reefs. They are protected from predators by the anemone's stinging tentacles, to which they develop immunity through a specialized mucus layer. In exchange for protection, they aggressively defend the anemone from butterflyfish and provide vital nutrients via their waste. They typically live in small groups consisting of a breeding pair and several non-breeding males.",
        funFact: "All Clownfish are born male; they have the ability to switch their sex to become the dominant female if the current female dies."
    },
    {
        name: "Regal Blue Tang",
        cat: "Fish",
        rarity: "uncommon",
        status: "LC",
        size: "25cm - 30cm",
        danger: 1,
        population: "Stable",
        depth: "2m - 40m",
        temp: "24°C - 26°C",
        time: "Day",
        season: "All Year",
        diet: "Herbivore",
        geo: "Indo-Pacific",
        desc: "Recognizable by its vibrant electric-blue body and bold yellow tail, this species is a critical member of the reef community. They play a vital role in reef health by grazing on excess algae that would otherwise smother and kill the coral polyps. Despite their friendly appearance in popular media, they possess sharp, scalpel-like spines near their tail base for defense against predators. They are social fish that often form large schools to forage along the reef edge.",
        funFact: "When threatened, they often 'play dead' by flopping onto their side and remaining motionless until the danger passes."
    },
    {
        name: "Hawksbill Sea Turtle",
        cat: "Turtle",
        rarity: "legendary",
        status: "CR",
        size: "60cm - 90cm",
        danger: 0,
        population: "Approx. 20,000",
        depth: "0m - 20m",
        temp: "25°C - 29°C",
        time: "Day",
        season: "All Year",
        diet: "Spongivore",
        geo: "Global / Tropical",
        desc: "Distinguished by their hawk-like beak and beautiful overlapping shell scales, these turtles are a rare sight on modern reefs. They are essential to reef biodiversity because they specialize in eating sea sponges, which prevents the sponges from outcompeting the coral for limited space. Their shells were historically hunted for 'tortoiseshell' jewelry, leading to their current Critically Endangered status. They prefer nesting on small, secluded tropical beaches across the globe.",
        funFact: "Their shells are biofluorescent, meaning they can absorb light and re-emit it as a different color, usually glowing green or red."
    },
    {
        name: "Reef Stonefish",
        cat: "Fish",
        rarity: "rare",
        status: "LC",
        size: "30cm - 40cm",
        danger: 5,
        population: "Stable",
        depth: "0m - 30m",
        temp: "22°C - 28°C",
        time: "Day/Night",
        season: "All Year",
        diet: "Carnivore",
        geo: "Indo-Pacific",
        desc: "The most venomous fish in the world, the Reef Stonefish is a master of biological camouflage. It mimics the texture and color of a rough stone or piece of coral perfectly, making it nearly invisible to both prey and humans. It sits motionless on the seabed for hours, waiting to ambush small fish and crustaceans with a suction-strike that takes only milliseconds. Their dorsal spines are capable of piercing through rubber soles, injecting a lethal neurotoxin.",
        funFact: "Their dorsal spines are strong enough to pierce through the sole of a shoe, delivering a toxin that can be fatal to humans without treatment."
    },
    {
        name: "Whitetip Reef Shark",
        cat: "Shark",
        rarity: "uncommon",
        status: "VU",
        size: "1.5m - 1.7m",
        danger: 2,
        population: "Decreasing",
        depth: "8m - 40m",
        temp: "26°C - 29°C",
        time: "Night",
        season: "All Year",
        diet: "Carnivore",
        geo: "Indo-Pacific / Central Pacific",
        desc: "A small, slender shark easily identified by the white tips on its dorsal and upper tail fins. Unlike many shark species that must swim to breathe, Whitetips can pump water over their gills while stationary. This allows them to spend their days resting in caves or on sandy bottoms, often stacked together in groups. At night, they become highly active and agile hunters, using their thin bodies to navigate tight crevices in the reef to find sleeping fish.",
        funFact: "They are social hunters at night, often working in groups to flush fish out of tight crevices in the coral."
    },
    {
        name: "Queen Angelfish",
        cat: "Fish",
        rarity: "uncommon",
        size: "25cm - 45cm",
        geo: "Western Atlantic / Caribbean",
        temp: "22°C - 28°C",
        depth: "1m - 70m",
        status: "LC",
        danger: 0,
        population: "Stable",
        time: "Day",
        season: "All Year",
        diet: "Spongivore",
        desc: "Easily one of the most beautiful reef dwellers, the Queen Angelfish is distinguished by its vibrant blue 'crown' on its forehead. They are social but shy, often found in pairs or small groups weaving through coral heads. Their long, flowing fins and bright yellow-to-blue gradient make them a favorite for photographers, though they are quick to tuck into crevices when approached.",
        funFact: "They specialize in eating sea sponges that are toxic to most other fish, thanks to a highly specialized digestive tract."
    },
    {
        name: "Giant Oceanic Manta Ray",
        cat: "Ray",
        rarity: "legendary",
        size: "7.0m - 9.0m",
        geo: "Global / Pelagic",
        temp: "20°C - 30°C",
        depth: "0m - 1000m",
        status: "EN",
        danger: 0,
        population: "Decreasing",
        time: "Day/Night",
        season: "Migration Based",
        diet: "Planktivore",
        desc: "Unlike the smaller Reef Manta, the Giant Oceanic Manta is a true wanderer of the open sea. These massive filter feeders are known for their high intelligence and long-distance migrations across entire oceans. They possess the largest brain-to-body ratio of any fish, often showing genuine curiosity and recognition toward humans in the water. They are frequently seen at 'cleaning stations' where small fish remove parasites from their skin.",
        funFact: "Every Manta has a completely unique pattern of spots on its belly, which researchers use like a fingerprint to identify individuals."
    },
    {
        name: "Blue Whale",
        cat: "Mammal",
        rarity: "legendary",
        size: "24m - 30m",
        geo: "Global / Deep Ocean",
        temp: "1°C - 25°C",
        depth: "0m - 500m",
        status: "EN",
        danger: 0,
        population: "10,000 - 25,000",
        time: "Day/Night",
        season: "Seasonal Migration",
        diet: "Planktivore",
        desc: "The largest animal to ever exist on Earth, even bigger than the largest dinosaurs. Blue Whales are graceful giants that sustain their massive bulk almost entirely on tiny shrimp-like krill, consuming up to 4 tons a day. Their hearts are the size of a bumper car, and their low-frequency calls can travel hundreds of miles across the ocean, allowing them to communicate across vast distances.",
        funFact: "A Blue Whale's tongue alone can weigh as much as an entire elephant!"
    },
    {
        name: "Leafy Seadragon",
        cat: "Fish",
        rarity: "epic",
        size: "20cm - 24cm",
        geo: "Southern Australia",
        temp: "13°C - 19°C",
        depth: "3m - 30m",
        status: "LC",
        danger: 0,
        population: "Stable / Protected",
        time: "Day",
        season: "Summer (Breeding)",
        diet: "Carnivore",
        desc: "A relative of the seahorse, the Leafy Seadragon is the gold standard of marine camouflage. Its body is covered in leaf-like appendages that serve no purpose for movement; instead, they allow the dragon to perfectly mimic drifting seaweed. They have no teeth and no stomach, requiring them to hunt almost constantly for tiny mysid shrimp which they swallow whole through their long, straw-like snouts.",
        funFact: "Just like seahorses, the males are the ones that carry the eggs, which are tucked into a 'brood patch' under their tail."
    },
    {
        name: "Box Jellyfish",
        cat: "Invertebrate",
        rarity: "epic",
        size: "20cm - 30cm (Bell)",
        geo: "Indo-Pacific / Northern Australia",
        temp: "25°C - 31°C",
        depth: "0m - 5m",
        status: "LC",
        danger: 5,
        population: "Seasonal / Abundant",
        time: "Day",
        season: "Summer (Stinger Season)",
        diet: "Carnivore",
        desc: "One of the most venomous creatures in the world, the Box Jellyfish is significantly more advanced than other jellies. Unlike most jellyfish that drift blindly, Box Jellies have 24 eyes and are capable of swimming purposefully toward prey. Their tentacles are lined with thousands of nematocysts that deliver a venom so powerful it can cause cardiac arrest in humans within minutes. They are mostly found in shallow coastal waters during the warmer months.",
        funFact: "They are one of the only jellyfish species with 'true' eyes that include retinas, corneas, and lenses."
    },
    {
        name: "Hammerhead Shark",
        cat: "Shark",
        rarity: "rare",
        size: "3.5m - 6.0m",
        geo: "Global / Tropical & Temperate",
        temp: "20°C - 28°C",
        depth: "0m - 500m",
        status: "CR",
        danger: 4,
        population: "Decreasing",
        time: "Day/Night",
        season: "All Year",
        diet: "Carnivore",
        desc: "Easily identified by their unique hammer-shaped heads, known as cephalofoils. This shape gives them 360-degree vision and an expanded area for their electroreceptors, allowing them to sweep the seafloor for hidden prey like a metal detector. They are particularly famous for their favorite food: stingrays, which they pin to the sand using their wide heads.",
        funFact: "They are one of the few animals that can tan! Their skin darkens when they spend long periods in shallow, sunlit waters."
    },
    {
        name: "Humpback Whale",
        cat: "Mammal",
        rarity: "epic",
        size: "13m - 16m",
        geo: "Global / Pelagic",
        temp: "1°C - 28°C",
        depth: "0m - 200m",
        status: "LC",
        danger: 0,
        population: "Approx. 84,000",
        time: "Day/Night",
        season: "Seasonal Migration",
        diet: "Planktivore",
        desc: "Famous for their complex, haunting songs that can last for hours and travel huge distances. Humpbacks are the most acrobatic of the great whales, frequently breaching and slapping the water with their massive pectoral fins. They use a clever cooperative hunting method called 'bubble-net feeding,' where a group blows a circle of bubbles to trap schools of fish before swimming up through the center.",
        funFact: "A Humpback's pectoral fins are the largest appendages of any animal, reaching up to one-third of their body length."
    },
    {
        name: "Giant Moray Eel",
        cat: "Fish",
        rarity: "uncommon",
        size: "2.5m - 3.0m",
        geo: "Indo-Pacific",
        temp: "24°C - 29°C",
        depth: "1m - 50m",
        status: "LC",
        danger: 3,
        population: "Stable",
        time: "Night",
        season: "All Year",
        diet: "Carnivore",
        desc: "The largest of the moray eels, these predators are staples of the tropical reef. They spend their days tucked into crevices with only their heads poking out, constantly opening and closing their mouths. While this looks aggressive, it’s actually how they pump water over their gills to breathe. They have a second set of jaws in their throat, known as pharyngeal jaws, which reach forward to drag prey down.",
        funFact: "They often engage in 'cooperative hunting' with Groupers—a rare example of two different fish species working together to find food."
    },
    {
        name: "Flamboyant Sepia",
        cat: "Cephalopod",
        rarity: "rare",
        size: "6cm - 8cm",
        geo: "Indo-Pacific / Australia",
        temp: "22°C - 27°C",
        depth: "3m - 80m",
        status: "DD",
        danger: 4,
        population: "Unknown",
        time: "Day",
        season: "All Year",
        diet: "Carnivore",
        desc: "Despite its tiny size, this is one of the most visually stunning creatures in the sea. Unlike other cuttlefish that swim, the Flamboyant Sepia often 'walks' along the seafloor using its tentacles. When threatened, its skin erupts into pulsing patterns of bright yellow, purple, and red. This display is a warning: like the Blue-Ringed Octopus, its muscle tissue is highly toxic.",
        funFact: "It is the only cuttlefish species known to have toxic flesh, making it as deadly as it is beautiful."
    },
    {
        name: "Dugong",
        cat: "Mammal",
        rarity: "rare",
        size: "2.5m - 3.0m",
        geo: "Indo-West Pacific",
        temp: "20°C - 30°C",
        depth: "1m - 10m",
        status: "VU",
        danger: 0,
        population: "Decreasing",
        time: "Day",
        season: "All Year",
        diet: "Herbivore",
        desc: "Often called 'Sea Cows,' Dugongs are gentle herbivores that spend their entire lives in shallow coastal waters grazing on seagrass. They are closely related to manatees but can be distinguished by their fluked, dolphin-like tails. They are very slow-moving and social animals, often leaving 'trails' in seagrass meadows where they have been feeding. They can live for up to 70 years in protected environments.",
        funFact: "Ancient sailors often mistook Dugongs for mermaids, which is why their scientific order is named 'Sirenia'."
    }


];
